Bitirme/Models/Maliyet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliyet
    {
        public int MaliyetId { get; set; }
        public Nullable<int> GiderId { get; set; }
        public Nullable<int> FaaliyetId { get; set; }
        public Nullable<int> KMEId { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Faaliyet Faaliyet { get; set; }
        public virtual Gider Gider { get; set; }
        public virtual KaynakMaliyetEtken KaynakMaliyetEtken { get; set; }
    }
}

Bitirme/Controllers/MaliyetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bitirme.Models;

namespace Bitirme.Controllers
{
    public class MaliyetController : Controller
    {
        BitirmeEntities db = new BitirmeEntities();
        // GET: Maliyet
        public ActionResult Index()
        {
            var maliyet = db.Maliyets.ToList();
            return View(maliyet);
        }
        [HttpGet]
        public ActionResult Create()
        {
            List<SelectListItem> M_Gider = (from i in db.Giders.ToList()
                                            select new SelectListItem
                                            {
                                        
                                                Text =i.HesapKodu+" "+i.HesapAd,
                                                Value = i.GiderId.ToString(),
                                            }
                                            ).ToList();
            M_Gider.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            ViewBag.MGider = M_Gider;
            List<SelectListItem> M_Faaliyet = (from i in db.Faaliyets.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = i.FaaliyetAd,
                                                   Value = i.FaaliyetId.ToString()
                                               }
                                             ).ToList();
            M_Faaliyet.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            ViewBag.Mfaaliyet = M_Faaliyet;

            List<SelectListItem> M_KaynakMaliyetEtken = (from i in db.KaynakMaliyetEtkens.ToList()
                                                         select new SelectListItem
                                                         {
                                                             Text = i.KMEAd,
                                                             Value = i.KMEId.ToString(),
                                                         }
                                                        ).ToList();
            M_KaynakMaliyetEtken.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            ViewBag.Mkme = M_KaynakMaliyetEtken;

            return View();
        }
        [HttpPost]
        public ActionResult Create(Maliyet parametre)
        {

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            else
            {
               

                    List<SelectListItem> M_Gider = (from i in db.Giders.ToList()
                                                select new SelectListItem
                                                {

                                                    Text = i.HesapKodu + " " + i.HesapAd,
                                                    Value = i.GiderId.ToString(),
                                                }
                                           ).ToList();
              
                ViewData["MGider"] = M_Gider;
                List<SelectListItem> M_Faaliyet = (from i in db.Faaliyets.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = i.FaaliyetAd,
                                                       Value = i.FaaliyetId.ToString()
                                                   }
                                                 ).ToList();

                ViewData["Mfaaliyet"] = M_Faaliyet;

                List<SelectListItem> M_KaynakMaliyetEtken = (from i in db.KaynakMaliyetEtkens.ToList()
                                                             select new SelectListItem
                                                             {
                                                                 Text = i.KMEAd,
                                                                 Value = i.KMEId.ToString(),
                                                             }
                                                            ).ToList();

                ViewData["Mkme"] = M_KaynakMaliyetEtken;


                var mukerrer = db.Maliyets.Where(ba => ba.GiderId == parametre.Gider.GiderId && ba.FaaliyetId==parametre.Faaliyet.FaaliyetId && ba.KMEId==parametre.KaynakMaliyetEtken.KMEId && ba.Onay.ToString()==parametre.Onay.ToString()).FirstOrDefault();
                if (mukerrer == null)
                {

                    var Gider = db.Giders.Where(ba => ba.GiderId == parametre.Gider.GiderId).FirstOrDefault();
                    parametre.Gider = Gider;

                    var faaliyet = db.Faaliyets.Where(ba => ba.FaaliyetId == parametre.Faaliyet.FaaliyetId).FirstOrDefault();
                    parametre.Faaliyet = faaliyet;

                    var kme = db.KaynakMaliyetEtkens.Where(ba => ba.KMEId == parametre.KaynakMaliyetEtken.KMEId).FirstOrDefault();
                    parametre.KaynakMaliyetEtken = kme;

                    db.Maliyets.Add(parametre);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View();
            }
            
            
        }
        public ActionResult Remove(int id)
        {
            var maliyet = db.Maliyets.Find(id);
            db.Maliyets.Remove(maliyet);

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            List<SelectListItem> M_Gider = (from i in db.Giders.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.HesapKodu + " " + i.HesapAd,
                                                Value = i.GiderId.ToString(),
                                            }
                                          ).ToList();
            ViewBag.MGider = M_Gider;
            List<SelectListItem> M_Faaliyet = (from i in db.Faaliyets.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = i.FaaliyetAd,
                                                   Value = i.FaaliyetId.ToString()
                                               }
                                             ).ToList();
            ViewBag.Mfaaliyet = M_Faaliyet;

            List<SelectListItem> M_KaynakMaliyetEtken = (from i in db.KaynakMaliyetEtkens.ToList()
                                                         select new SelectListItem
                                                         {
                                                             Text = i.KMEAd,
                                                             Value = i.KMEId.ToString(),
                                                         }
                                                        ).ToList();
            ViewBag.Mkme = M_KaynakMaliyetEtken;
            var maliyet=db.Maliyets.Find(id);
            return View(maliyet);

        }
        public ActionResult Edit(Maliyet parametre)
        {
            var mukerrer = db.Maliyets.Where(ba => ba.GiderId == parametre.Gider.GiderId && ba.FaaliyetId == parametre.Faaliyet.FaaliyetId && ba.KMEId == parametre.KaynakMaliyetEtken.KMEId && ba.Onay.ToString() == parametre.Onay.ToString()).FirstOrDefault();
            if (mukerrer == null)
            {

                var m = db.Maliyets.Find(parametre.MaliyetId);

                m.Adet = parametre.Adet;

                var mGider = db.Giders.Where(ba => ba.GiderId == parametre.Gider.GiderId).FirstOrDefault();
                m.GiderId = mGider.GiderId;

                var mfaaliyet = db.Faaliyets.Where(ba => ba.FaaliyetId == parametre.Faaliyet.FaaliyetId).FirstOrDefault();
                m.FaaliyetId = mfaaliyet.FaaliyetId;

                var mKaynakMaliyetEtken = db.KaynakMaliyetEtkens.Where(ba => ba.KMEId == parametre.KaynakMaliyetEtken.KMEId).FirstOrDefault();
                m.KMEId = mKaynakMaliyetEtken.KMEId;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var id = parametre.MaliyetId;
            string yol = "Details/" + id.ToString();
            return RedirectToAction(yol);

        }

    }
}

Bitirme/Views/Maliyet/Create.cshtml
@using Bitirme.Models
@model Maliyet
@{
    ViewBag.Title = "Create";
}
<form method="post" class="form-group">
    <div>
        <label>Giderler</label>
        @Html.DropDownListFor(ba => ba.Gider.GiderId, (List<SelectListItem>)ViewData["Mgider"], new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.Gider.GiderId, "", new { @style = "color.red" })

    </div>
    <div>


        <label>Kaynak Maliyet Etkenleri</label>
        @Html.DropDownListFor(ba => ba.KaynakMaliyetEtken.KMEId, (List<SelectListItem>)ViewData["Mkme"], new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.KaynakMaliyetEtken.KMEId, "", new { @style = "color.red" })

    </div>
    <div>


        <label>Faaliyet</label>
        @Html.DropDownListFor(ba => ba.Faaliyet.FaaliyetId, (List<SelectListItem>)ViewData["Mfaaliyet"], new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.Faaliyet.FaaliyetId, "", new { @style = "color.red" })

    </div>

    <div>
        <label>Onay</label>
        @Html.DropDownListFor(ba => ba.Onay, new List<SelectListItem>() { new SelectListItem() { Text = "---Lütfen Seçiniz---" }, new SelectListItem() { Text = "Aktif", Value = "True" }, new SelectListItem() { Text = "Pasif", Value = "False" } }, new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.Onay, "", new { @style = "color.red" })
    </div>
    @*<div>
        <label>Onay</label>
        @Html.DropDownListFor(ba => ba.Onay, new List<SelectListItem>() { new SelectListItem() { Text = "Aktif", Value = "True" }, new SelectListItem() { Text = "Pasif", Value = "False" } }, new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.Onay, "", new { @style = "color.red" })
    </div>*@
    <div>

        <label>Adet</label>
        @Html.TextBoxFor(ba => ba.Adet, new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.Onay, "", new { @style = "color.red" })
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Ekle</button>
    </div>
</form>

Bitirme/Views/Maliyet/Details.cshtml
@using Bitirme.Models
@model Maliyet

@using (Html.BeginForm("Edit", "Maliyet", FormMethod.Post))
{

<div class="form-group">
    <div>
        @Html.LabelFor(ba => ba.MaliyetId)
        @Html.TextBoxFor(ba => ba.MaliyetId)


    </div>
    <div>
        <label>Gider</label>
        @Html.DropDownListFor(ba => ba.Gider.GiderId, (List<SelectListItem>)ViewBag.Mgider, new { @class = "form-control" })
    </div>
    <div>
        <label>Faaliyet</label>
        @Html.DropDownListFor(ba => ba.Faaliyet.FaaliyetId, (List<SelectListItem>)ViewBag.Mfaaliyet, new { @class = "form-control" })
    </div>
    <div>
        <label>Kaynak Maliyet Etken</label>
        @Html.DropDownListFor(ba => ba.KaynakMaliyetEtken.KMEId, (List<SelectListItem>)ViewBag.Mkme, new { @class = "form-control" })
    </div>
    <div>
        <label>Onay</label>
        @Html.DropDownListFor(ba => ba.Onay, new List<SelectListItem>() { new SelectListItem() { Text = "Aktif", Value = "True" }, new SelectListItem() { Text = "Pasif", Value = "False" } }, new { @class = "form-control" })

    </div>
    @*<div>
        <label>Adet</label>
        <input type="number" name="Adet" class="form-control" placeholder="Adet" />
    </div>*@
    <div>
        <label>Adet</label>
        @Html.TextBoxFor(ba => ba.Adet, new { @class = "form-control" })
    </div>
    <br />
</div>
        <div style="margin-top:15px">
            <button class="btn btn-info">Ekle</button>
        </div>
        }

Bitirme/Views/Maliyet/Index.cshtml
@using Bitirme.Models
@model List<Maliyet>

@{
    ViewBag.Title = "Index";
}


<table id="mytbl" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Gider </th>
            <th scope="col">Kaynak Maliyet Etken </th>
            <th scope="col">Faaliyet </th>

            <th scope="col">Onay </th>
            <th scope="col">Adet </th>
            <th scope="col">Sil </th>
            <th scope="col">Güncelle </th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            var sayi = string.Format("{0:n0}", item.Adet);
            <tr>
                <td> @item.Gider.HesapKodu @item.Gider.HesapAd </td>
                <td> @item.KaynakMaliyetEtken.KMEAd </td>
                <td> @item.Faaliyet.FaaliyetAd</td>

                @if (item.Onay==true)
                {
            <td>
                Aktif
            </td>
                }
                else
                {
                    <td> Pasif</td>
                }
           
                <td> @sayi </td>
                <td>@Html.ActionLink("Sil ", "Remove", new { id = item.MaliyetId }, new { @class = "btn btn-warning" })</td>
                <td>@Html.ActionLink("Güncelle", "Details", new { id = item.MaliyetId }, new { @class = "btn btn-success" })</td>

            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Yeni Maliyet Ekle", "Create", "Maliyet")

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>
<script>
    $('#mytbl').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });

</script>