Bitirme/Models/Urun.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.BirimMaliyets = new HashSet<BirimMaliyet>();
            this.MaliyetUruns = new HashSet<MaliyetUrun>();
        }
    
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BirimMaliyet> BirimMaliyets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaliyetUrun> MaliyetUruns { get; set; }
    }
}

Bitirme/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bitirme.Models;

namespace Bitirme.Controllers
{
    public class UrunController : Controller
    {
        BitirmeEntities db = new BitirmeEntities();
        // GET: Urun
        public ActionResult Index()
        {
            var Uruns = db.Uruns.ToList();
            return View(Uruns);
        }
        public ActionResult Remove(int id)
        {
            var remove = db.Uruns.Find(id);
            db.Uruns.Remove(remove);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            var edit = db.Uruns.Find(id);
            return View(edit);
        }
        public ActionResult Edit(Urun parametre)
        {

            var mukerrer = db.Uruns.Where(ba => ba.UrunAd == parametre.UrunAd).FirstOrDefault();
            if (mukerrer == null)
            {
                var Urunum = db.Uruns.Find(parametre.UrunId);
                Urunum.UrunAd = parametre.UrunAd;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var id = parametre.UrunId;
            string yolu = "Details/" + id.ToString();
            return RedirectToAction(yolu);

        }
        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(Urun parametre)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                var mukerrer = db.Uruns.Where(ba => ba.UrunAd == parametre.UrunAd).FirstOrDefault();
                if (mukerrer==null)
                {
                    db.Uruns.Add(parametre);
                db.SaveChanges();
                return RedirectToAction("Index");

                }
                return View();

            }
            
            
        }
    }
}

Bitirme/Views/Urun/Create.cshtml
@using Bitirme.Models
@model Urun
@{
    ViewBag.Title = "Create";
}

<form class=" form-group" method="post">
    <div>
        @Html.Label("Ürün Adı")
        @Html.TextBoxFor(ba => ba.UrunAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.UrunAd,"",new { @style = "color:red" })
    </div>


    <div style="margin-top:15px">
        <button class="btn btn-info">Urun Ekle</button>
    </div>
</form>

Bitirme/Views/Urun/Details.cshtml
@using Bitirme.Models
@model Urun
@{
    ViewBag.Title = "Details";
}

@using (Html.BeginForm("Edit", "Urun", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(ba => ba.UrunId)
        @Html.TextBoxFor(ba => ba.UrunId)
        <br />
        @Html.LabelFor(ba => ba.UrunAd)
        @Html.TextBoxFor(ba => ba.UrunAd)
    </div>

    <div>
        <button class="btn btn-warning">Urun Güncelle   </button>
    </div>
}

Bitirme/Views/Urun/Index.cshtml
@using Bitirme.Models
@model List<Urun>
@{
    ViewBag.Title = "Index";
}


<table id="mytbl" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Urun Ad</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td> @item.UrunAd </td>
                <td>@Html.ActionLink("Sil", "Remove", new { id = item.UrunId }, new { @class = "btn btn-warning" })</td>
                <td>@Html.ActionLink("Güncelleme", "Details", new { id = item.UrunId }, new { @class = "btn btn-success" })</td>

            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Yeni Urun Ekle", "Create", "Urun")
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>
<script>
    $('#mytbl').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });

</script>