Bitirme/Models/Faaliyet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faaliyet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faaliyet()
        {
            this.DagitimOlcuFaaliyetiliskis = new HashSet<DagitimOlcuFaaliyetiliski>();
            this.Maliyets = new HashSet<Maliyet>();
        }
    
        public int FaaliyetId { get; set; }
        public string FaaliyetAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DagitimOlcuFaaliyetiliski> DagitimOlcuFaaliyetiliskis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maliyet> Maliyets { get; set; }
    }
}

Bitirme/Controllers/FaaliyetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bitirme.Models;

namespace Bitirme.Controllers
{
    public class FaaliyetController : Controller
    {
        BitirmeEntities db = new BitirmeEntities();
        // GET: Faaliyet
        public ActionResult Index()
        {
            var Faaliyet = db.Faaliyets.ToList();
            return View(Faaliyet);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Faaliyet parametre)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }
            else
            {
                var mukerrer = db.Faaliyets.Where(ba => ba.FaaliyetAd == parametre.FaaliyetAd).FirstOrDefault();
                if (mukerrer==null)
                {
                db.Faaliyets.Add(parametre);
                db.SaveChanges();
                return RedirectToAction("Index");
                }
                return View();
               
            }

        }
        public ActionResult Remove(int id) 
        {
            var remove = db.Faaliyets.Find(id);
            db.Faaliyets.Remove(remove);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            var edit = db.Faaliyets.Find(id);
            return View(edit);
        }
        public ActionResult Edit(Faaliyet parametre)
        {
            var mukerrer = db.Faaliyets.Where(ba => ba.FaaliyetAd == parametre.FaaliyetAd).FirstOrDefault();
            if (mukerrer == null)
            {
                var faaliyetdeger = db.Faaliyets.Find(parametre.FaaliyetId);
                faaliyetdeger.FaaliyetAd = parametre.FaaliyetAd;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var id = parametre.FaaliyetId;
            string yolu = "Details/" + id.ToString();
            return RedirectToAction(yolu);

        }

    }
}

Bitirme/Views/Faaliyet/Create.cshtml
@using Bitirme.Models
@model Faaliyet
@{
    ViewBag.Title = "Create";
}

<form class=" form-group" method="post">
    <div>
        @Html.Label("Faaliyet Adı")  @Html.TextBoxFor(ba => ba.FaaliyetAd, new { @class = "form-control" })
        @Html.ValidationMessageFor(ba => ba.FaaliyetAd, "", new { @style = "color:red" })
    </div>
  

    <div style="margin-top:15px">
        <button class="btn btn-info">Faaliyet Ekle</button>
    </div>
</form>

Bitirme/Views/Faaliyet/Details.cshtml
@using Bitirme.Models
@model Faaliyet
@{
    ViewBag.Title = "Details";
}

@using (Html.BeginForm("Edit", "Faaliyet", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(ba => ba.FaaliyetId)
        @Html.TextBoxFor(ba => ba.FaaliyetId)
        <br />
        @Html.LabelFor(ba => ba.FaaliyetAd)
        @Html.TextBoxFor(ba => ba.FaaliyetAd)
    </div>

    <div>
        <button class="btn btn-warning">Faaliyet Güncelle   </button>
    </div>
}

Bitirme/Views/Faaliyet/Index.cshtml
@using Bitirme.Models
@model List<Faaliyet>
@{
    ViewBag.Title = "Index";
}
<table id="mytbl" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Faaliyet Ad</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td> @item.FaaliyetAd </td>
                <td>@Html.ActionLink("Sil", "Remove", new { id = item.FaaliyetId }, new { @class = "btn btn-warning" })</td>
                <td>@Html.ActionLink("Güncelleme", "Details", new { id = item.FaaliyetId }, new { @class = "btn btn-success" })</td>

            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Yeni Faaliyet Ekle", "Create", "Faaliyet")
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>


<script>
  
        $('#mytbl').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
            }
        });
   

</script>