Bitirme/Models/BirimMaliyetTutar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirimMaliyetTutar
    {
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> EndirektToplam { get; set; }
        public Nullable<decimal> Dimmg { get; set; }
        public Nullable<decimal> Dig { get; set; }
        public Nullable<decimal> ToplamMaliyet { get; set; }
        public Nullable<int> BirimDagitimOlcu { get; set; }
        public int MaliyetUrunId { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> DagitimOlcuId { get; set; }
        public Nullable<decimal> UrunDagitimAdet { get; set; }
        public Nullable<decimal> BirimMaliyet { get; set; }
    }
}

Bitirme/Models/ToplamMaliyet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToplamMaliyet
    {
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> EndirektToplam { get; set; }
        public Nullable<decimal> Dimmg { get; set; }
        public Nullable<decimal> Dig { get; set; }
        public Nullable<decimal> ToplamMaliyet1 { get; set; }
        public Nullable<int> BirimDagitimOlcu { get; set; }
        public Nullable<int> Urun_ID { get; set; }
    }
}

Bitirme/Controllers/BirimMaliyetiController.cs
using Bitirme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bitirme.Controllers
{
    public class BirimMaliyetiController : Controller
    {
        // GET: BirimMaliyeti
        BitirmeEntities db = new BitirmeEntities();
        public ActionResult Index()
        {
            var objects = db.BirimMaliyets.ToList();
            return View(objects);
        }
        public ActionResult ToplamMaliyet()
        {
            var ba = db.SPToplamMaliyet();
            return View(ba);
        }
        public ActionResult BirimMaliyetTutar()
        {
            var ba = db.BirimMaliyetSP1();
            return View(ba);
        }
        [HttpGet]
        public ActionResult Create()
        {
            
            List<SelectListItem> urun = (from i in db.Uruns.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.UrunAd,
                                             Value = i.UrunId.ToString(),
                                         }
                                         ).ToList();
            urun.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            List<SelectListItem> dagitim = (from i in db.DagıtımOlcu.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.DagıtımOlcu_Ad,
                                             Value = i.DagıtımOlcu_Id.ToString(),
                                         }
                                         ).ToList();
            dagitim.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            ViewBag.Dagitim = dagitim;
            ViewBag.Urunler = urun;
            return View();
        }
        [HttpPost]
        public ActionResult Create(BirimMaliyet parametre)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                
                    db.BirimMaliyets.Add(parametre);
                    db.SaveChanges();
                    return RedirectToAction("Index");      
            }


        }
        public ActionResult Remove(int id)
        {
            var remove = db.BirimMaliyets.Find(id);
            db.BirimMaliyets.Remove(remove);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {

            List<SelectListItem> urun = (from i in db.Uruns.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.UrunAd,
                                             Value = i.UrunId.ToString(),
                                         }
                                         ).ToList();
            urun.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            List<SelectListItem> dagitim = (from i in db.DagıtımOlcu.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.DagıtımOlcu_Ad,
                                                Value = i.DagıtımOlcu_Id.ToString(),
                                            }
                                         ).ToList();
            dagitim.Insert(0, new SelectListItem()
            {
                Value = "0",
                Text = "-- Lütfen Seçiniz --"
            });
            ViewBag.Dagitim = dagitim;
            ViewBag.Urunler = urun;

            var data = db.BirimMaliyets.Find(id);
            return View(data);
        }
        public ActionResult Edit(BirimMaliyet parametre)
        {
           

                var m = db.BirimMaliyets.Find(parametre.BM_Id);

                m.Dimmg = parametre.Dimmg;
                m.Dig = parametre.Dig;

                var m_urun = db.Uruns.Where(ba => ba.UrunId == parametre.Urun.UrunId).FirstOrDefault();
                m.Urun_ID = m_urun.UrunId;

            var dd = db.DagıtımOlcu.Where(ba => ba.DagıtımOlcu_Id == parametre.DagıtımOlcu.DagıtımOlcu_Id).FirstOrDefault();
            m.BirimDagitimOlcu = dd.DagıtımOlcu_Id;

            db.SaveChanges();
                return RedirectToAction("Index");
           
        }


    }

}

Bitirme/Views/BirimMaliyeti/BirimMaliyetTutar.cshtml
@{
    ViewBag.Title = "BirimMaliyetTutar";
}

@using Bitirme.Models


<table id="mytbl" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID </th>
            <th scope="col">Ürün </th>
            <th scope="col">EUM</th>
            <th scope="col">Dimmg</th>
            <th scope="col">Dig</th>
            <th scope="col">Toplam Maliyet</th>
            <th scope="col">Birim Maliyet</th>


        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            var sayi = string.Format("{0:N2}", item.ToplamMaliyet);
            <tr>

                <td>@item.BMT_ID</td>
                <td>@item.Urunler</td>
                <td>@item.EndirekUM</td>
                <td>@item.Dimmg</td>
                <td>@item.Dig</td>
                <td>@sayi</td>
                <td>@item.BirimMaliyet</td>
            </tr>
        }
    </tbody>
</table>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>
<script>
    $('#mytbl').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });

</script>

Bitirme/Views/BirimMaliyeti/Create.cshtml
@using Bitirme.Models
@model BirimMaliyet
@{
    ViewBag.Title = "Create";
}

<form class=" form-group" method="post">

    <div>
        @Html.Label("Urun")
        @Html.DropDownListFor(ba => ba.Urun_ID, (List<SelectListItem>)ViewBag.Urunler, new { @class = "form-control" })
     

    </div>
       
    <div>
        @Html.Label("Dimmg")
        @Html.TextBoxFor(ba => ba.Dimmg, new { @class = "form-control" })

    </div>
    <div>
        @Html.Label("Dig")
        @Html.TextBoxFor(ba => ba.Dig, new { @class = "form-control" })

    </div>
    <div>
        @Html.Label("Dağitim Ölçüsü")
        @Html.DropDownListFor(ba => ba.BirimDagitimOlcu, (List<SelectListItem>)ViewBag.Dagitim, new { @class = "form-control" })


    </div>


    <div style="margin-top:15px">
        <button class="btn btn-info">Birime Ekle</button>
    </div>
</form>

Bitirme/Views/BirimMaliyeti/Details.cshtml
@using Bitirme.Models
@model BirimMaliyet
@{
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm("Edit", "BirimMaliyeti", FormMethod.Post))
{


    <div>
        @Html.LabelFor(ba => ba.BM_Id)
        @Html.TextBoxFor(ba => ba.BM_Id)


    </div>

    <div>
        <label>Urun</label>
        @Html.DropDownListFor(ba => ba.Urun.UrunId, (List<SelectListItem>)ViewBag.Urunler, new { @class = "form-control" })
    </div>
    
    <div>
        <label>Dİmmg</label>
        @Html.TextBoxFor(ba => ba.Dimmg, new { @class = "form-control" })
    </div>
    <div>
        <label>Adet</label>
        @Html.TextBoxFor(ba => ba.Dig, new { @class = "form-control" })
    </div>
    <div>
        <label>Dağıtım Ölçüsü</label>
        @Html.DropDownListFor(ba => ba.DagıtımOlcu.DagıtımOlcu_Id, (List<SelectListItem>)ViewBag.Dagitim, new { @class = "form-control" })
    </div>



    <div style="margin-top:15px">
        <button class="btn btn-info">Ekle</button>
    </div>
}

Bitirme/Views/BirimMaliyeti/Index.cshtml
@using Bitirme.Models
@model List<BirimMaliyet>
@{
    ViewBag.Title = "Index";
}


<table id="mytbl" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Urun</th>

            <th scope="col">Dimmg</th>
            <th scope="col">Dig</th>
            <th scope="col">Dağıtım Ölçü</th>

            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td> @item.BM_Id </td>
                <td> @item.Urun.UrunAd</td>

                <td> @item.Dimmg </td>
                <td> @item.Dig </td>
                <td> @item.DagıtımOlcu.DagıtımOlcu_Ad </td>

                <td>@Html.ActionLink("Sil", "Remove", new { id = item.BM_Id }, new { @class = "btn btn-warning" })</td>
                <td>@Html.ActionLink("Güncelleme", "Details", new { id = item.BM_Id }, new { @class = "btn btn-success" })</td>

            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Ekle", "Create", "BirimMaliyeti")
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>
<script>
    $('#mytbl').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });

</script>

Bitirme/Views/BirimMaliyeti/ToplamMaliyet.cshtml
@{
    ViewBag.Title = "ToplamMaliyet";
}
@using Bitirme.Models

<table id="mytbl" class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID </th>
            <th scope="col">Ürün </th>
            <th scope="col">EUM</th>
            <th scope="col">Dimmg</th>
            <th scope="col">Dig</th>
            <th scope="col">Toplam Maliyet</th>
            

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            var sayi = string.Format("{0:N2}", item.ToplamMaliyeti);
            <tr>

                <td>@item.TMaliyet_ID</td>
                <td>@item.UrunAdi</td>
                <td>@item.EndirektToplami</td>
                <td>@item.Dimmg</td>
                <td>@item.Dig</td>
                <td>@sayi</td>
            </tr>
        }
    </tbody>
</table>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/rg-1.0.0/datatables.min.js"></script>
<script>
    $('#mytbl').DataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });

</script>